name: PEGA7
description: Pega7 installation
version: 0
category: Test
maintainer: Test # The maintainer of the Catalog entry
license: Test # The license
projectURL: Test # The URL related to the Catalog entry
