name: PEGA7
description: Pega7 PRPC
version: 0
category: ERP
maintainer: Salim Ibrahim # The maintainer of the Catalog entry
license: Pegasystems Inc. # The license
projectURL: http://www.pega.com # The URL related to the Catalog entry
