.catalog:
  name: Pega
version: '2'
services:
  installer:
    scale: 1
    start_on_create: true
  tomcat:
    scale: 1
    start_on_create: true
  postgres:
    scale: 1
    start_on_create: true
