catalog:
  name: "PEGA7"
  version: "v1"
  description: "PEGA7"
  uuid: pega7-1
version: '2'
services:
  installer:
    scale: 1
    start_on_create: true
  tomcat:
    scale: 1
    start_on_create: true
  postgres:
    scale: 1
    start_on_create: true
